print("       我是長長長長頸鹿喔～!           ")
print("                                       ")
print("         _  o o                        ")
print("          \\  \\|/ _,                  ")
print("      __.'   /`_/                      ")
print("    /`    u   #                        ")
print("    `c-_..__,/ ##                      ")
print("           ):'##                       ")
print("           |   ##                      ")
print("           |:.:##                      ")
for i in range(int(input('長度'))):
    print("           |   ##                      ")
    print("           |:.:##                      ")
print("           |.  ##                      ")
print("           |:.'##                      ")
print("           |.  ##                      ")
print("          /  ' ##                      ")
print("          |.:'  ##                     ")
print("          ::' .:#                      ")
print("         / '     '#                    ")
print("         |  .: '::.`'-..__             ")
print("         |:.         .::' `',          ")
print("         |:::   ':.       .:, \\       ")
print("           \\ ', .  .::' .::  | |      ")
print("          |'.|.:|  '     '  / \\#      ")
print("          |   \\ '|._.::  |   |##      ")
print("          | /|.:|  `""`| .:|##         ")
print("          / ||  /     |   '|           ")
print("           \\ // |     \\:'   \\       ")
print("          | / \\ /      |  \\          ")
print("          | || |       | || /          ")
print("          | || |       | || |          ")
print("         _/ j| |      _/ J| |          ")
print("        (/_/_/ J     (/_/_/ j          ")
print("           (/_/         (/_/           ")